### ISSUE TITLE
test_h2matrix failure

### ISSUE THREAD

**Issue by d-meiser** [H2Lib/H2Lib#1]
Hi, not sure if this is a false positive but I'm getting a test failure in `test_h2matrix`. The output from the test is as follows:

```
dmeiser@longspeak:/home/scratch/H2Lib/Tests (master)$ ./test_h2matrix 
----------------------------------------
Check 579 x 579 Cholesky factorization
Creating laplacebem2d SLP matrix
Creating random solution and right-hand side
Copying matrix
Computing Cholesky factorization
Solving
  Accuracy 2.07929e-12,     NOT okay
Checking factorization
  Accuracy 3.57875e-14, okay
----------------------------------------
Check 579 x 579 LR factorization
Creating laplacebem2d SLP matrix
Creating random solution and right-hand side
Copying matrix
Computing LR factorization
Solving
  Accuracy 1.61567e-12, okay
Checking factorization
  Accuracy 3.14747e-14, okay
Cleaning up
----------------------------------------
  0 matrices and
  0 vectors still active
  1 errors found
```
This is with the `make.inc.unix_release` configuration with gcc 4.4 on centos 6.3 with system blas and lapack on that system (pre-compiled atlas from centos repository).

**Comment by sboerm** [comment]
Hallo Dominic.

> Hi, not sure if this is a false positive but I'm getting a test
> failure in |test_h2matrix|. The output from the test is as follows:

Kein Grund zur Sorge, da ist wohl nur die Genauigkeitsanforderung im
Testprogramm zu scharf eingestellt. Wir testen meistens mit LAPACK, und
dessen Singulärwertzerlegung ist genauer als die, die ich mir selbst
zusammengebastelt habe.

Ich kümmere mich darum, dass das angepasst wird.

Schöne Grüße,
Steffen

**Comment by sboerm** [comment]
Hallo Dominic.

Ja, das Problem trat bei mir auch auf. In "make.inc.release" sind BLAS
und LAPACK abgeschaltet, also werden meine Ersatzfunktionen verwendet.
Und deren SVD ist nicht so gut wie die in LAPACK.

Ich habe die Genauigkeiten im Testprogramm etwas angepasst, Du findest
die aktualisierte Fassung bei GitHub.

Die H^2-Matrix-Arithmetik ist allerdings noch in einem sehr
experimentellen Stadium: Die weltweit erste Implementierung ;-)

Schöne Grüße,
Steffen

**Comment by d-meiser** [comment]
Hallo Steffen,

Vielen Dank fuer die schnelle Antwort. Konnte das Verhalten das du beschreibst auch bei mir reproduzieren: Wenn ich mit blas/lapack uebersetze ist der Test in Ordnung.

Bin uebrigens sehr beeindruckt von H2lib. Vielen Dank dass du und deine Gruppe die Bibliothek ins Netz gestellt habt.

Gruss,
Dominic

**Comment by sboerm** [comment]
Hallo Dominic.

> Vielen Dank fuer die schnelle Antwort.

Gern geschehen, vielen Dank zurück für den Hinweis. Unsere eigenen
Testprogramme sollten schließlich schon funktionieren ;-)

> Konnte das Verhalten das du beschreibst auch bei mir reproduzieren:
> Wenn ich mit blas/lapack uebersetze ist der Test in Ordnung.

Sehr gut.

> Bin uebrigens sehr beeindruckt von H2lib.

Dankeschön, das gebe ich gerne an meine Leute weiter.

> Vielen Dank dass du und deine Gruppe die Bibliothek ins Netz gestellt
> habt.

Keine Ursache. Ich hoffe, dass durch freie Software (und die
Winterschule) die Einstiegshürden bei H- und H²-Matrizen etwas gesenkt
werden.

Schöne Grüße,
bis morgen,
Steffen
