### ISSUE TITLE
Using H2Lib in C++

### ISSUE THREAD

**Issue by cgraeser** [H2Lib/H2Lib#15]
While settings.h looks like being prepared for use in a C++ program, including H2Lib headers in C++ fails for me. It seems that there are two main issues:

* The definition of `INLINE_PREFIX` in the `__cplusplus` branch does not compile because `static extern "C"` seems to be not allowed. Since the purpose of `extern "C"` is to change linkage to C-style in C++ it's maybe OK to just drop `extern "C"` for `static` C functions because they should not be linked to from user code.
* H2Lib defines `bool`, `true`, and `false` which is not compatible with C++ because these are reserved keywords in C++ and not just macros. Enclosing the definition with `#ifdef __cplusplus` fixes the error during compilation but may lead to linker errors because C++ assumes corresponding arguments are real C++ `bool`s while they are `unsigned short` in the compiled H2Lib library.

A proper fix for the `bool` issue could be to use `BOOL`, `TRUE`, `FALSE` instead. But before preparing a patch I'd like to know if there is interest in such an invasive change.

**Comment by sboerm** [comment]
Hi, Carsten.

>   * The definition of |INLINE_PREFIX| in the |__cplusplus| branch does
>     not compile because |static extern "C"| seems to be not allowed.

If your C compiler supports C99, you could simply set INLINE_PREFIX to
"inline". I hope that this should work with C++, as well.

>   * H2Lib defines |bool|, |true|, and |false| which is not compatible
>     with C++ because these are reserved keywords in C++ and not just
>     macros.

C99 might be the answer: include stdbool.h and delete the definitions in
our header file. I hope that the C++ and C99 APIs are compatible.

The definitions of INLINE_PREFIX and our own Boolean type were only
included to ensure compatibility with pre-C99 compilers. Since we now
need C99 for complex numbers anyway, we could simply drop them.

Best regards,
Steffen

**Comment by cgraeser** [comment]
Hi Steffen,
in C++ `inline` is what you want. In C99 this does not work for me. I don't completely understand this in C99, but it seems that `static inline` is what you want in there.

For compatibility C++ also has `stdbool.h`. Although it's not guaranteed that the C++ build in type `bool` is the same as the C99 build in type `_Bool` which is mapped to `bool` in this header are compatible, it's likely to be true if the compilers come from the same vendor. I just checked this with gcc 5.2 and it seems to work.

After fixing these, and some missing HEADER_PREFIX statements, I can use H2Lib in C++. At leastI compiling `test_amatrix.c` as C++ while linking against H2Lib build with C works for me.

I'll provide the needed patches against the community branch.

**Comment by cgraeser** [comment]
OK, I pushed the fixes and opened pull requests for each individual issue: #16, #17, #18.
The library and tests compile and run successfully for me when applying these changes.
Furthermore I checked that `test_amatrix.c` can be compiled with C++ and linked against the H2Lib lib build with C.

#16, #17 should only influence the behaviour with C++ and have no effect when compiling with C.

In contrast #18 will change the type of bool by using `stdbool.h`. Notice that this will break the ABI, because the `bool` defined in this header is in fact the C99 build-in type `_Bool` which for gcc turnes out to have 1 byte (like the C++ `bool`) in contrast to the `unsigned short` used now. However, without such a change H2Lib can never be used in C++ unless all occurrences of `bool`, `true`, and `false` are replaced by macros that are not C++ keywords.

**Comment by schristophersen** [comment]
Hi Carsten,

I added all your pull requests to the community branch. I'm going to test the changes on my machines the next days too and see if there are any problems occuring with pure C-compilers.

Thanks a lot and best regards,
Sven
