### ISSUE TITLE
H2Lib as a dynamic library?

### ISSUE THREAD

**Issue by PetrKryslUCSD** [H2Lib/H2Lib#27]
Hi,

I have tried to build the library as a shared library (dynamic) on Linux. Unfortunately none of the tests or examples than work: they crash with a segmentation fault. 

Has this been attempted before (i. e. linking the examples with a dynamic library instead of a static library)?
Did it work?

**Comment by sboerm** [comment]
Hi.
We have tried to build a shared library, and I think that it worked well on Linux. Since you get a segmentation fault, I assume that your executable is able to find the shared library.
Does Linux still require position-independent code in shared libraries?
Could you run the program in a debugger and let me know where exactly the segmentation fault occurs?
Best regards, Steffen

**Comment by PetrKryslUCSD** [comment]
Hi Steffen, 

I'm afraid the problem was of my own doing. I passed the -shared flag to the linker of the programs by mistake. (The linked programs don't like that! Hence the crashes.)

I'd be happy to create a PR once I polish the configuration options to build both the static and the dynamic version of the library.

In case you're interested: I would like to build a Julia interface to your library. Hence I need a dynamically-linked library to begin with. I also need a few additional functions within your library because I am not linking with the library, and I'm dynamically calling functions some of which may not be available because they were written as static. Again, if there is interest I could create a PR.

Petr

**Comment by sboerm** [comment]
Hi Petr.
Interesting! Did the Linker try to turn the main program into a shared library?
A PR for the Community branch would certainly be very welcome :-)
And a Julia interface could make H2Lib much more accessible, so I would also like to incorporate a PR for that into the Community branch. I do not have much experience with interfaces to interpreted languages, so it would be interesting to see how to do it.
Best regards, Steffen

**Comment by PetrKryslUCSD** [comment]
Hi Steffen,
I think that, as you say, the executables got infected with sharing :) It was even impossible to debug as the stack at crash consisted of no-name functions.

The PRs: will do. If you'd like to have a look at the Julia interface, visit my github page. I look forward to your comments.

P
